In [1]:
import pandas as pd
import os
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVR
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

In [2]:
csv_path = os.path.join("..", "..", "data","LINKED_DATA", "TSR_EHR", "TSR_1_CLEANED.csv")
tsr_1 = pd.read_csv(csv_path)
tsr_1.head()

height_nm  weight_nm  edu_id  pro_id  opc_id  ih_fl  ivtpamg_nm  \
0      150.0       49.0       2       1       3      0         0.0   
1      153.0       62.0       3       1       3      0         0.0   
2      152.0       62.0       3       1       2      0         0.0   
3      148.0       56.0       2       1       2      0         0.0   
4      152.0       56.0       4       1       2      0         0.0   

   hospitalised_time  nivtpa_id  nivtpa1_fl  ...  nihs_6br_out  nihs_7_out  \
0               16.0          1           0  ...             0           0   
1                8.0          0         999  ...             0           1   
2                4.0          0         999  ...             0           0   
3                5.0          0         999  ...             0           0   
4                3.0          1           0  ...             0           0   

   nihs_8_out  nihs_9_out  nihs_10_out  nihs_11_out  total_out  SexName   Age  \
0           0           0            0            0          8        0  66.0   
1           1           0            1            0          4        0  67.0   
2           1           0            0            0          1        0  69.0   
3           1           0            0            0          2        0  71.0   
4           0           0            0            0          0        0  71.0   

   mrs_tx_1  
0         4  
1         1  
2         1  
3         0  
4         0  

[5 rows x 307 columns]

In [3]:
tsr_1_input = tsr_1.drop(["mrs_tx_1"], axis=1)
tsr_1_input[tsr_1_input == "N"] = 0
tsr_1_input[tsr_1_input == "Y"] = 1
tsr_1_input = tsr_1_input.astype("float64")
tsr_1_input = np.array(tsr_1_input.values)

# 6 classes

In [4]:
tsr_1_output = tsr_1.mrs_tx_1
tsr_1_output = tsr_1_output.astype("float64")
tsr_1_output = np.array(tsr_1_output.values)

## SVM

In [5]:
svr = LinearSVR(epsilon = 0, dual=False, loss = "squared_epsilon_insensitive", C = 1, random_state = 19)
svr_scores = cross_val_score(svr,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(svr_scores)
print("Mean of R^2:", svr_scores.mean())
print("Std of R^2:", svr_scores.std())

[0.75819834 0.81292278 0.81497893 0.81372612 0.81603806 0.84767392
 0.79382794 0.80927838 0.72774844 0.66216536]
Mean of R^2: 0.7856558275219963
Std of R^2: 0.0520984455211836


In [6]:
acc_svr = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    svr.fit(X_train,y_train)
    svr_predict = svr.predict(X_test)
    print(svr_predict)
    svr_predict = np.round(svr_predict)
    print(svr_predict)
    accuracy = (y_test == svr_predict).sum() / len(svr_predict)
    acc_svr.append(accuracy)

print("Accuracy of RF:", acc_svr)
print("Mean of Accuracy of RF:", sum(acc_svr)/10)

[3.63177721 3.92400339 0.85621053 ... 0.69885322 2.40144137 4.72461155]
[4. 4. 1. ... 1. 2. 5.]
[3.10429887 3.61039415 0.97839168 ... 4.65710068 3.13195641 0.85689758]
[3. 4. 1. ... 5. 3. 1.]
[1.24068413 4.66920173 3.6043923  ... 1.00194716 0.73332832 0.99244565]
[1. 5. 4. ... 1. 1. 1.]
[3.06628029 0.47666973 2.19192225 ... 1.0359054  4.39173202 4.87944934]
[3. 0. 2. ... 1. 4. 5.]
[4.21537147 3.24487551 1.0375099  ... 4.81919014 4.23136026 1.42139614]
[4. 3. 1. ... 5. 4. 1.]
[3.0279219  2.76907962 1.09506645 ... 5.25919745 0.8978008  0.76661463]
[3. 3. 1. ... 5. 1. 1.]
[2.24914909 1.17393331 4.35869342 ... 1.04460957 1.63876947 1.20621253]
[2. 1. 4. ... 1. 2. 1.]
[4.33542943 1.18419696 5.13708587 ... 4.94419828 1.95881699 4.51639772]
[4. 1. 5. ... 5. 2. 5.]
[3.35576071 4.76918169 1.21815003 ... 1.03077389 1.32571587 1.82449149]
[3. 5. 1. ... 1. 1. 2.]
[3.15666364 1.90539683 0.78873033 ... 4.18909527 4.86717298 0.75379426]
[3. 2. 1. ... 4. 5. 1.]
Accuracy of RF: [0.5930864197530864, 0.5

In [7]:
svr_pred = cross_val_predict(svr,tsr_1_input,tsr_1_output,cv = 10)
svr_pred = np.round(svr_pred)
confusion_matrix(tsr_1_output, svr_pred)

array([[  23,  452,   69,   13,    0,    1,    0],
       [   2,  963,  254,   40,    8,    2,    0],
       [   1,  318,  472,  128,   12,    1,    0],
       [   0,   24,  239,  494,   94,    4,    0],
       [   0,   13,   44,  347,  861,  235,    0],
       [   0,    8,   22,   35,  361, 1177,   32],
       [   0,    0,    0,    0,    0,    0,    0]], dtype=int64)

In [8]:
svr_pred[svr_pred == -1] = 0
svr_pred[svr_pred == 6] = 5
confusion_matrix(tsr_1_output, svr_pred)

array([[  23,  452,   69,   13,    0,    1],
       [   2,  963,  254,   40,    8,    2],
       [   1,  318,  472,  128,   12,    1],
       [   0,   24,  239,  494,   94,    4],
       [   0,   13,   44,  347,  861,  235],
       [   0,    8,   22,   35,  361, 1209]], dtype=int64)

## RF

In [9]:
rfr = RandomForestRegressor(criterion = "mse", n_estimators = 15, bootstrap=True, random_state = 19,max_features = 0.8)
rfr_scores = cross_val_score(rfr,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(rfr_scores)
print("Mean of R^2:", rfr_scores.mean())
print("Std of R^2:", rfr_scores.std())

[0.80253601 0.85442144 0.84661287 0.83234409 0.854438   0.87123276
 0.82762541 0.88558175 0.78763589 0.80643935]
Mean of R^2: 0.8368867559211093
Std of R^2: 0.029832924726383228


In [10]:
acc_rfr = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    rfr.fit(X_train,y_train)
    rfr_predict = rfr.predict(X_test)
    print(rfr_predict)
    rfr_predict = np.round(rfr_predict)
    print(rfr_predict)
    accuracy = (y_test == rfr_predict).sum() / len(rfr_predict)
    acc_rfr.append(accuracy)

print("Accuracy of RF:", acc_rfr)
print("Mean of Accuracy of RF:", sum(acc_rfr)/10)

[3.93333333 3.66666667 1.2        ... 0.8        3.06666667 4.93333333]
[4. 4. 1. ... 1. 3. 5.]
[2.73333333 3.06666667 0.86666667 ... 5.         2.86666667 1.        ]
[3. 3. 1. ... 5. 3. 1.]
[1.26666667 2.33333333 3.93333333 ... 1.26666667 0.13333333 0.66666667]
[1. 2. 4. ... 1. 0. 1.]
[3.86666667 0.         1.6        ... 1.         4.46666667 4.2       ]
[4. 0. 2. ... 1. 4. 4.]
[3.93333333 2.66666667 0.93333333 ... 5.         4.06666667 1.        ]
[4. 3. 1. ... 5. 4. 1.]
[2.4        2.73333333 0.93333333 ... 5.         0.93333333 0.33333333]
[2. 3. 1. ... 5. 1. 0.]
[1.86666667 1.33333333 3.8        ... 0.93333333 1.66666667 1.73333333]
[2. 1. 4. ... 1. 2. 2.]
[4.         0.93333333 5.         ... 4.93333333 2.4        5.        ]
[4. 1. 5. ... 5. 2. 5.]
[3.93333333 5.         1.73333333 ... 2.         2.         1.73333333]
[4. 5. 2. ... 2. 2. 2.]
[3.06666667 1.26666667 1.         ... 4.13333333 3.86666667 0.06666667]
[3. 1. 1. ... 4. 4. 0.]
Accuracy of RF: [0.7175308641975309, 0.7

In [11]:
rfr_pred = cross_val_predict(rfr,tsr_1_input,tsr_1_output,cv = 10)
rfr_pred = np.round(rfr_pred)
confusion_matrix(tsr_1_output, rfr_pred)

array([[ 340,  172,   29,   16,    0,    1],
       [  74,  881,  258,   43,   11,    2],
       [   3,  117,  648,  146,   18,    0],
       [   0,   16,  166,  515,  151,    7],
       [   0,   14,   29,  222, 1105,  130],
       [   0,    4,   13,   31,  291, 1296]], dtype=int64)

## XGBoost

In [12]:
xgbr = XGBRegressor(n_estimators  = 15, objective="reg:squarederror", random_state = 19) 
xgbr_scores = cross_val_score(xgbr,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(xgbr_scores)
print("Mean of R^2:", xgbr_scores.mean())
print("Std of R^2:", xgbr_scores.std())

[0.81509538 0.85465433 0.85629336 0.84323481 0.85948638 0.87759867
 0.82663422 0.88904219 0.79003615 0.8080127 ]
Mean of R^2: 0.8420088202986703
Std of R^2: 0.029945460047586483


In [13]:
acc_xgbr = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    xgbr.fit(X_train,y_train)
    xgbr_predict = xgbr.predict(X_test)
    print(xgbr_predict)
    xgbr_predict = np.round(xgbr_predict)
    print(xgbr_predict)
    accuracy = (y_test == xgbr_predict).sum() / len(xgbr_predict)
    acc_xgbr.append(accuracy)

print("Accuracy of RF:", acc_xgbr)
print("Mean of Accuracy of RF:", sum(acc_xgbr)/10)

[3.8546104  3.6603224  0.7762871  ... 0.70660627 2.6783786  4.7589192 ]
[4. 4. 1. ... 1. 3. 5.]
[2.6323295  3.2563019  0.6803381  ... 4.7454863  2.8813007  0.87798727]
[3. 3. 1. ... 5. 3. 1.]
[1.5723697  0.69949096 3.6528234  ... 1.4687432  0.23287195 0.81369287]
[2. 1. 4. ... 1. 0. 1.]
[4.004202   0.14587125 2.4357052  ... 1.1030616  4.5037174  4.4187326 ]
[4. 0. 2. ... 1. 5. 4.]
[4.4327884 2.8224654 1.1039562 ... 4.9666066 4.2781777 0.9271805]
[4. 3. 1. ... 5. 4. 1.]
[2.2888973  2.7285707  0.92034024 ... 4.918951   0.8411906  0.09822913]
[2. 3. 1. ... 5. 1. 0.]
[2.2669735  1.8406572  4.007482   ... 0.83611053 1.6631366  1.5614779 ]
[2. 2. 4. ... 1. 2. 2.]
[4.2538114  0.88671076 4.975448   ... 4.863804   1.4232424  4.7189164 ]
[4. 1. 5. ... 5. 1. 5.]
[3.7776914 4.9771314 1.5965321 ... 1.8973361 1.6836715 1.9208057]
[4. 5. 2. ... 2. 2. 2.]
[3.2637565  1.86057    0.87550443 ... 4.057502   2.9755042  0.07775678]
[3. 2. 1. ... 4. 3. 0.]
Accuracy of RF: [0.7125925925925926, 0.7185185185185

In [14]:
xgbr_pred = cross_val_predict(xgbr,tsr_1_input,tsr_1_output,cv = 10)
xgbr_pred = np.round(xgbr_pred)
confusion_matrix(tsr_1_output, xgbr_pred)

array([[ 350,  159,   34,   14,    0,    1],
       [  72,  881,  259,   46,    9,    2],
       [   3,   92,  682,  139,   16,    0],
       [   0,   14,  167,  518,  149,    7],
       [   0,   12,   36,  183, 1135,  134],
       [   0,    4,   15,   29,  290, 1297]], dtype=int64)

# 2 classes

In [15]:
tsr_1_output[(tsr_1_output == 0)|(tsr_1_output == 1)|(tsr_1_output == 2)] = 0
tsr_1_output[(tsr_1_output == 3)|(tsr_1_output == 4)|(tsr_1_output == 5)] = 1

## SVM

In [16]:
svr2 = LinearSVR(epsilon = 0, dual=False, loss = "squared_epsilon_insensitive", C = 1, random_state = 19)
svr_scores2 = cross_val_score(svr2,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(svr_scores2)
print("Mean of R^2:", svr_scores2.mean())
print("Std of R^2:", svr_scores2.std())

[0.65463265 0.67281146 0.72629149 0.72803586 0.72637818 0.71985612
 0.69138906 0.72825933 0.45705818 0.55765237]
Mean of R^2: 0.6662364692825355
Std of R^2: 0.086093723164523


In [17]:
acc_svr2 = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    svr2.fit(X_train,y_train)
    svr2_predict = svr2.predict(X_test)
    print(svr2_predict)
    svr2_predict = np.round(svr2_predict)
    print(svr2_predict)
    accuracy = (y_test == svr2_predict).sum() / len(svr2_predict)
    acc_svr2.append(accuracy)

print("Accuracy of RF:", acc_svr2)
print("Mean of Accuracy of RF:", sum(acc_svr2)/10)

[ 0.86036502  0.93726979 -0.03260337 ...  0.02071565  0.48623117
  0.98929883]
[ 1.  1. -0. ...  0.  0.  1.]
[ 0.70028179  0.778855   -0.01234504 ...  0.98553506  0.68842572
  0.00662048]
[ 1.  1. -0. ...  1.  1.  0.]
[8.73535662e-02 1.02015739e+00 9.66945408e-01 ... 1.84902588e-02
 3.72523815e-04 4.31560911e-02]
[0. 1. 1. ... 0. 0. 0.]
[ 0.65755903 -0.04314598  0.42838713 ... -0.01517854  1.0170974
  1.15831568]
[ 1. -0.  0. ... -0.  1.  1.]
[1.01385814 0.70825689 0.01622801 ... 0.92674531 1.04881492 0.17890742]
[1. 1. 0. ... 1. 1. 0.]
[ 0.64637231  0.52490535  0.04709503 ...  1.02731749 -0.00438992
 -0.02045528]
[ 1.  1.  0. ...  1. -0. -0.]
[ 0.5054601   0.04438553  1.09594979 ... -0.01506389  0.28518703
  0.019087  ]
[ 1.  0.  1. ... -0.  0.  0.]
[0.99661007 0.02877895 1.0430751  ... 0.99380175 0.26781615 0.89397794]
[1. 0. 1. ... 1. 0. 1.]
[ 0.70559041  1.03745375  0.04037606 ... -0.00119915  0.0836765
  0.22710506]
[ 1.  1.  0. ... -0.  0.  0.]
[0.70883368 0.31781983 0.00213649 .

In [18]:
svr_pred2 = cross_val_predict(svr2,tsr_1_input,tsr_1_output,cv = 10)
svr_pred2 = np.round(svr_pred2)
confusion_matrix(tsr_1_output, svr_pred2)

array([[2523,  236],
       [ 332, 3658]], dtype=int64)

## RF

In [19]:
rfr2 = RandomForestRegressor(criterion = "mse", n_estimators = 15, bootstrap=True, random_state = 19,max_features = 0.8)
rfr_scores2 = cross_val_score(rfr2,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(rfr_scores2)
print("Mean of R^2:", rfr_scores2.mean())
print("Std of R^2:", rfr_scores2.std())

[0.70414766 0.78598706 0.80979341 0.80851794 0.74737315 0.76380059
 0.76552779 0.78078116 0.65483732 0.72780284]
Mean of R^2: 0.7548568911288809
Std of R^2: 0.04593017505732098


In [20]:
acc_rfr2 = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    rfr2.fit(X_train,y_train)
    rfr2_predict = rfr2.predict(X_test)
    print(rfr2_predict)
    rfr2_predict = np.round(rfr2_predict)
    print(rfr2_predict)
    accuracy = (y_test == rfr2_predict).sum() / len(rfr2_predict)
    acc_rfr2.append(accuracy)

print("Accuracy of RF:", acc_rfr2)
print("Mean of Accuracy of RF:", sum(acc_rfr2)/10)

[0.93333333 0.93333333 0.         ... 0.06666667 0.8        1.        ]
[1. 1. 0. ... 0. 1. 1.]
[0.6        0.86666667 0.06666667 ... 1.         0.86666667 0.        ]
[1. 1. 0. ... 1. 1. 0.]
[0.         0.33333333 1.         ... 0.         0.2        0.        ]
[0. 0. 1. ... 0. 0. 0.]
[0.86666667 0.         0.66666667 ... 0.06666667 1.         1.        ]
[1. 0. 1. ... 0. 1. 1.]
[0.6        0.8        0.06666667 ... 1.         1.         0.        ]
[1. 1. 0. ... 1. 1. 0.]
[0.26666667 0.93333333 0.         ... 1.         0.         0.        ]
[0. 1. 0. ... 1. 0. 0.]
[0.13333333 0.         1.         ... 0.         0.         0.        ]
[0. 0. 1. ... 0. 0. 0.]
[1.         0.         1.         ... 1.         0.46666667 1.        ]
[1. 0. 1. ... 1. 0. 1.]
[1.         1.         0.         ... 0.33333333 0.         0.06666667]
[1. 1. 0. ... 0. 0. 0.]
[0.93333333 0.2        0.         ... 0.86666667 0.73333333 0.        ]
[1. 0. 0. ... 1. 1. 0.]
Accuracy of RF: [0.9323456790123457, 0.9

In [21]:
rf_pred2 = cross_val_predict(rfr2,tsr_1_input,tsr_1_output,cv = 10)
rf_pred2 = np.round(rf_pred2)
confusion_matrix(tsr_1_output, rf_pred2)

array([[2495,  264],
       [ 171, 3819]], dtype=int64)

## XGBoost

In [22]:
xgbr2 = XGBRegressor(n_estimators  = 15, objective="reg:squarederror", random_state = 19) 
xgbr_scores2 = cross_val_score(xgbr2,tsr_1_input,tsr_1_output,cv = 10, scoring='r2')
print(xgbr_scores2)
print("Mean of R^2:", xgbr_scores2.mean())
print("Std of R^2:", xgbr_scores2.std())

[0.72319331 0.79790321 0.80933179 0.80348947 0.7580319  0.78636109
 0.76204846 0.81063156 0.68175723 0.76111351]
Mean of R^2: 0.769386151505116
Std of R^2: 0.03952853476472426


In [23]:
acc_xgbr2 = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(tsr_1_input, tsr_1_output, test_size=0.3, random_state=i)
    xgbr2.fit(X_train,y_train)
    xgbr2_predict = xgbr2.predict(X_test)
    print(xgbr2_predict)
    xgbr2_predict = np.round(xgbr2_predict)
    print(xgbr2_predict)
    accuracy = (y_test == xgbr2_predict).sum() / len(xgbr2_predict)
    acc_xgbr2.append(accuracy)

print("Accuracy of RF:", acc_xgbr2)
print("Mean of Accuracy of RF:", sum(acc_xgbr2)/10)

[ 0.9495655   0.89795643 -0.00250822 ...  0.00600568  0.6823147
  0.9911568 ]
[ 1.  1. -0. ...  0.  1.  1.]
[ 4.1323084e-01  8.2266897e-01 -4.1745983e-02 ...  1.0234411e+00
  8.4449166e-01  4.2145932e-04]
[ 0.  1. -0. ...  1.  1.  0.]
[0.0016398  0.25492936 1.0039567  ... 0.0016398  0.1673533  0.00969216]
[0. 0. 1. ... 0. 0. 0.]
[0.9335647  0.00117021 0.60321623 ... 0.02443131 0.9723783  1.0178573 ]
[1. 0. 1. ... 0. 1. 1.]
[1.0229796  0.6489199  0.00894728 ... 1.0086251  1.0035559  0.18061362]
[1. 1. 0. ... 1. 1. 0.]
[ 3.5655397e-01  9.9111605e-01  1.1931858e-02 ...  9.9738944e-01
 -5.6178244e-03  6.3104008e-04]
[ 0.  1.  0. ...  1. -0.  0.]
[0.29720703 0.14497171 1.0207148  ... 0.00304205 0.00583889 0.01310552]
[0. 0. 1. ... 0. 0. 0.]
[1.0068443  0.00653833 1.0122766  ... 0.99252546 0.2697963  0.9863429 ]
[1. 0. 1. ... 1. 0. 1.]
[0.98589385 1.0050402  0.00793168 ... 0.34443262 0.04761165 0.04781978]
[1. 1. 0. ... 0. 0. 0.]
[0.863824   0.18000661 0.0083073  ... 0.97610176 0.92521375 0.

In [24]:
xgbr_pred2 = cross_val_predict(xgbr2,tsr_1_input,tsr_1_output,cv = 10)
xgbr_pred2 = np.round(xgbr_pred2)
confusion_matrix(tsr_1_output, xgbr_pred2)

array([[2501,  258],
       [ 161, 3829]], dtype=int64)

# Summary

## Mean & Std

In [25]:
svr_mean = np.array([svr_scores.mean(), svr_scores.std(), svr_scores[0], svr_scores[1], svr_scores[2], svr_scores[3],
                     svr_scores[4], svr_scores[5], svr_scores[6], svr_scores[7], svr_scores[8], svr_scores[9]])
rfr_mean = np.array([rfr_scores.mean(), rfr_scores.std(), rfr_scores[0], rfr_scores[1], rfr_scores[2], rfr_scores[3],rfr_scores[4], 
                    rfr_scores[5], rfr_scores[6], rfr_scores[7], rfr_scores[8], rfr_scores[9]])
xgbr_mean = np.array([xgbr_scores.mean(), xgbr_scores.std(), xgbr_scores[0], xgbr_scores[1], xgbr_scores[2], xgbr_scores[3],
                     xgbr_scores[4], xgbr_scores[5], xgbr_scores[6], xgbr_scores[7], xgbr_scores[8], xgbr_scores[9]])
svr_mean2 = np.array([svr_scores2.mean(), svr_scores2.std(), svr_scores2[0], svr_scores2[1], svr_scores2[2], svr_scores2[3],
                     svr_scores2[4], svr_scores2[5], svr_scores2[6], svr_scores2[7], svr_scores2[8], svr_scores2[9]])
rfr_mean2 = np.array([rfr_scores2.mean(), rfr_scores2.std(), rfr_scores2[0], rfr_scores2[1], rfr_scores2[2], rfr_scores2[3],rfr_scores2[4], 
                    rfr_scores2[5], rfr_scores2[6], rfr_scores2[7], rfr_scores2[8], rfr_scores2[9]])
xgbr_mean2 = np.array([xgbr_scores2.mean(), xgbr_scores2.std(), xgbr_scores2[0], xgbr_scores2[1], xgbr_scores2[2], xgbr_scores2[3],
                     xgbr_scores2[4], xgbr_scores2[5], xgbr_scores2[6], xgbr_scores2[7], xgbr_scores2[8], xgbr_scores2[9]])

In [26]:
tsr_1_mean = pd.DataFrame([svr_mean, rfr_mean, xgbr_mean, svr_mean2, rfr_mean2, xgbr_mean2]).T
tsr_1_mean.index = ["Mean", "Std", "R^2_1", "R^2_2", "R^2_3", "R^2_4", "R^2_5", "R^2_6", "R^2_7", "R^2_8", "R^2_9", "R^2_10"]
tsr_1_mean.columns = ["svr", 'rfr', 'xgbr', 'svr2', 'rfr2', 'xgbr2']

In [27]:
csv_save = os.path.join(".", "tsr_1_mean_regression.csv")
tsr_1_mean.to_csv(csv_save, index = True)